version: '2'
services:

  dev:
    build: .
    volumes:
     - .:/usr/app/
    ports:
      - 8080:8080
    environment:
      - DBT_HOST=${CLICKHOUSE_HOST}
      - DBT_USER=${CLICKHOUSE_USER}
      - DBT_PASSWORD=${TF_VAR_clickhouse_password}
