config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

clickhouse_starschema:
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: "{{ env_var('DBT_HOST') }}" ##"rc1b-dfq55u84egt4unh9.mdb.yandexcloud.net"
      port: 8443
      user: "admin" # "{{ env_var('DBT_USER') }}" ##"admin"
      password: "clickhouse" #"{{ env_var('DBT_PASSWORD') }}" ##"clickhouse"
      secure: True
      verify: False
    ci:
      type: clickhouse
      host: clickhouse
      port: 8123
      schema: default
      threads: 4
  target: dev
